### ISSUE TITLE
deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. 

### ISSUE THREAD

**Issue by rbatllet** [karma-runner/karma-phantomjs-launcher#101]
Hello,

when I install `karma-phantomjs-launcher`, I get a warning message:

```
npm WARN `karma-phantomjs-launcher@0.2.3` requires a peer of phantomjs@>=1.9 but none was installed.
```
But when I install `phantomjs`, another warning message is displayed:

```
npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```

Please, replace the `phantomjs` references to `phantomjs-prebuild`.

**Comment by dignifiedquire** [comment]
please install the latest version which is 1.0.0

**Comment by rbatllet** [comment]
Now all the packages are installed with this new version without warnings !

Thanks!

**Comment by pcvandamcb** [comment]
If you are using npm 3, don't forget to also update your base phantomjs package to phantomjs-prebuilt, because it is a peer dependency.

**Comment by rbatllet** [comment]
I'm using `npm v3.5.3` and `node v5.5.0`

**Comment by mydeveloper1** [comment]
Question, any way of doing it in bulk? That is, performing this recommendation in bulk "Please update 'phantomjs' package references to 'phantomjs-prebuilt'?"
