### ISSUE TITLE
Upgrade to support Phantom 2.x

### ISSUE THREAD

**Issue by darrenhaken** [karma-runner/karma-phantomjs-launcher#109]
Hi,

Is this in the pipeline of work? Would you accept a PR to do this?

**Comment by dignifiedquire** [comment]
What exactly are you missing, the latest version has full support for PhantomJS 2: https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/package.json#L43

**Comment by darrenhaken** [comment]
Thanks for clarifying this, you're right it's using PhantomJS 2.

The project I was working on had 'phantomjs' and 'phantomjs-prebuilt' and I was looking at the wrong one. Has Phantom launcher always used prebuilt? If not when did it start?

**Comment by dignifiedquire** [comment]
It changed in v1.0.0, before it used `phantomjs` which got renamed to `phantomjs-prebuilt`.
