### ISSUE TITLE
Update phantomjs-prebuilt package

### ISSUE THREAD

**Issue by paladox** [karma-runner/karma-phantomjs-launcher#111]
Hi please update phantomjs-prebuilt package to 2.1.7 since they now download the binarys from there hosted release on GitHub. This now fixes the rate limit so builds should improve in download and installing stability.

And also please update phantomjs-prebuilt in peerDependencies to 2.1.7.

Also update karma in there too, to 0.13 please.

@vladikoff or @dignifiedquire could you please do ^^.

**Comment by tardyp** [comment]
why is this marked PR please, while karma-phantomjs-prebuilt already has following dep in package.json?

    "phantomjs-prebuilt": ">=1.9"

@paladox The only thing required is to add phantomjs-prebuild as a dependencies in your package, and fix the version you want.

**Comment by dignifiedquire** [comment]
You are totally right @tardyp closing.
