### ISSUE TITLE
Please Test code Using karma (Angularjs)

### ISSUE THREAD

**Issue by MakkaHareesh** [karma-runner/karma-phantomjs-launcher#122]
CONTROLLER:

function ctrlOperaterHome($scope,userService,srvcPeriod){
  $scope.getUserSelection = srvcPeriod.getSelection();
  $scope.objUser = {};
  $scope.objUser.userName = "";
  $scope.objUser.role = "";
  $scope.objUser.legalEntity = "";
  $scope.objUser.operator = "";
  $scope.objUser.circle = "";
  $scope.objUser.financialYear = srvcPeriod.getCurrentYear();
  $scope.objUser.quarter = srvcPeriod.getCurrentQuarter();

  $scope.aryObjLegalEntity = [];
  $scope.aryCircles = [];
  $scope.aryFNY = [];
  $scope.aryOperators = [];
  $scope.aryQuarters = [];
  $scope.aryLegalEntityNames = [];
  $scope.user = userService.getUser();
 // console.dir($scope.user)
  $scope.aryObjLegalEntity = $scope.user.legalEntity;
//  console.log($scope.aryObjLegalEntity)
  for(var i =0;i<=$scope.aryObjLegalEntity.length-1;i++){
    $scope.aryLegalEntityNames.push($scope.aryObjLegalEntity[i].strLegalEntity);
//    $scope.aryCircles.push($scope.aryLegalEntity[i].circles)
  }
  $scope.objUser.userName = $scope.user.strUserName;
  $scope.objUser.role = $scope.user.role;
  $scope.aryQuarters = srvcPeriod.getQuarters();
  $scope.aryFNY = srvcPeriod.getFYr();
  srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.getUserSelection.strLE,$scope.getUserSelection.strOpr,$scope.getUserSelection.strCrc,$scope.getUserSelection.strFYN,$scope.getUserSelection.strQutr);
 $scope.dropdowntriggerFunction = function(){
	 console.log('Trigger');
    $('#LegalEntity').dropdown({
      onChange:function(val){
        console.log(val);
        console.log("triggering");
        $scope.strCaPsLE = val.toUpperCase();
        $scope.objUser.legalEntity = $scope.strCaPsLE;
        srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.objUser.legalEntity,$scope.objUser.operator,$scope.objUser.circle,$scope.objUser.financialYear,$scope.objUser.quarter);
        for(var i =0;i<=$scope.aryObjLegalEntity.length-1;i++){
          if($scope.strCaPsLE == $scope.aryObjLegalEntity[i].strLegalEntity){
            $scope.aryCircles = [];
            $scope.aryOperators = [];
            $scope.aryCircles = $scope.aryObjLegalEntity[i].circles;
            $scope.aryOperators = $scope.aryObjLegalEntity[i].operator;
            $scope.$apply();
          }
        }

//        console.log($scope.objUser);
      }

    })
    $('#Operator').dropdown({
      onChange:function(val){
//        console.log(val);
        $scope.strCaPsOP = val.toUpperCase();
        $scope.objUser.operator = $scope.strCaPsOP;
        srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.objUser.legalEntity,$scope.objUser.operator,$scope.objUser.circle,$scope.objUser.financialYear,$scope.objUser.quarter);
        $scope.$apply();

//        console.log($scope.objUser);
      }

    })
     $('#Circle').dropdown({
      onChange:function(val){
//        console.log(val);
        $scope.strCaPsCRC = val.toUpperCase();
        $scope.objUser.circle = $scope.strCaPsCRC;
        srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.objUser.legalEntity,$scope.objUser.operator,$scope.objUser.circle,$scope.objUser.financialYear,$scope.objUser.quarter);
        $scope.$apply();

//        console.log($scope.objUser);
      }

    })
     $('#Quarter').dropdown({
      onChange:function(val){
//        console.log(val);
        $scope.strCaPsQR= val.toUpperCase();
        $scope.objUser.quarter = $scope.strCaPsQR;
        srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.objUser.legalEntity,$scope.objUser.operator,$scope.objUser.circle,$scope.objUser.financialYear,$scope.objUser.quarter);
        $scope.$apply();
//        console.log($scope.objUser);

      }
    })
     $('#FNY').dropdown({
      onChange:function(val){
//        console.log(val);
        $scope.objUser.financialYear = val;
        srvcPeriod.setSelection($scope.objUser.userName,$scope.objUser.role,$scope.objUser.legalEntity,$scope.objUser.operator,$scope.objUser.circle,$scope.objUser.financialYear,$scope.objUser.quarter);
        $scope.$apply();
      }
     })
  }
 $scope.dropdowntriggerFunction();
}
ctrlOperaterHome.$inject = ['$scope','userService','srvcPeriod'];
app.controller('ctrlOperaterHome',ctrlOperaterHome);

SPEC :
describe('Operator Executive Home Page Controller',function(){

    var MainCtrl,
        scope,
        userServiceInj,
        srvcPeriodInj,
				element;
	 var objData = {
					address : "",
					code : "executive login",
					legalEntity :[
						{
							CIN : "1234567895",
							circles : ["anp","upw"],
							code : "Airtel  Pvt Ltd",
							operator : ["vodafone","airtel"],
							startDate : "08/15/1947",
							strLegalEntity : "AIRTEL PVT LITMED",
							type : 3
						},
						{
							CIN : "123456",
							address : "",
							circles : ["anp","upw"],
							operator : ["vodafone"],
							strLegalEntity : "VODAFONE PVT LIMITED",
							type : 3
						}
					],
					loginType : "operator",
					processList : {},
					role : "",
					strUserName : ""
			};
	beforeEach(module('app'));
	beforeEach(inject(function ($controller, $rootScope,$compile,userService,srvcPeriod) {
    scope = $rootScope.$new();
    userServiceInj = userService;
    srvcPeriodInj = srvcPeriod;
		userServiceInj.setUser(objData);
    MainCtrl = $controller('ctrlOperaterHome', {
      $scope: scope,
    });
    }));

  it('should define getUserSelection',function(){
      expect(scope.getUserSelection).toBeDefined();
      expect(scope.getUserSelection).toEqual(srvcPeriodInj.getSelection());
    })
    it('should define objUser object and its properties',function(){
      expect(scope.objUser).toBeDefined();
      expect(scope.objUser.userName).toBeDefined();
      expect(scope.objUser.role).toBeDefined();
      expect(scope.objUser.legalEntity).toBeDefined();
      expect(scope.objUser.operator).toBeDefined();
      expect(scope.objUser.circle).toBeDefined();
      expect(scope.objUser.financialYear).toBeDefined();
      expect(scope.objUser.financialYear).toEqual(srvcPeriodInj.getCurrentYear())
      expect(scope.objUser.quarter).toBeDefined();
      expect(scope.objUser.quarter).toEqual(srvcPeriodInj.getCurrentQuarter())
    })

    it('should define Arrays',function(){
      expect(scope.aryObjLegalEntity).toBeDefined();
      expect(scope.aryCircles).toBeDefined();
      expect(scope.aryFNY).toBeDefined();
      expect(scope.aryOperators).toBeDefined();
      expect(scope.aryQuarters).toBeDefined();
      expect(scope.aryLegalEntityNames).toBeDefined();
    })

    it('should define user object',function(){
      expect(scope.user).toBeDefined();
      expect(scope.aryObjLegalEntity[0].CIN).toEqual("1234567895");
			expect(scope.aryObjLegalEntity[1].CIN).toEqual("123456");
    })
    it('Pushing legalentity names in to array',function(){
       expect(scope.aryLegalEntityNames).toEqual(["AIRTEL PVT LITMED", 'VODAFONE PVT LIMITED']);
    })
    it('should Assign objUser object key with values and assigning arrays',function(){
      expect(scope.objUser.userName).toEqual(scope.user.strUserName);
      expect(scope.objUser.role).toEqual(scope.user.role);
      expect(scope.aryQuarters).toEqual(srvcPeriodInj.getQuarters());
      expect(scope.aryFNY).toEqual(srvcPeriodInj.getFYr());
    })
    it('should set the data in servicePeriod service',function(){
		srvcPeriodInj.setSelection(scope.objUser.userName,scope.objUser.role,scope.getUserSelection.strLE,scope.getUserSelection.strOpr,scope.getUserSelection.strCrc,scope.getUserSelection.strFYN,scope.getUserSelection.strQutr)	
    })

		it('Dropdown to changes to values',inject(function($compile){
			scope.objUser.userName = "demouser" ;
			scope.objUser.role = "opeartor";
			scope.objUser.legalEntity = " airtel legalEntity";
			scope.objUser.operator= "airtel";
			//scope.$apply();
			scope.objUser.operator= "airtel";
			scope.objUser.circle= "ANP";
			scope.objUser.financialYear= "2015-2016";
			scope.objUser.quarter= "Q4";
			scope.dropdowntriggerFunction();
			//console.log(scope.dropdowntriggerFunction());
			scope.$digest();

		}))
});
please help me iam struck in jquery code testing

**Comment by dignifiedquire** [comment]
Please post questions like this on http://stackoverflow.com/. This repo is for tracking bugs in karma-phantomjs.
