### ISSUE TITLE
Bug in 1.0.3

### ISSUE THREAD

**Issue by silvioboehme** [karma-runner/karma-phantomjs-launcher#167]
commit 482eba50a1bcd0c97ae1d03bf4097c67577beb34 introduced a bug that breaks my ci build:

`return path.join(path.dirname(phantomSource), '//node_modules/' + phantomPackage._location + '//lib//phantom//', phantomPackage.bin.phantomjs)`

should be 

`return path.join(path.dirname(phantomSource), '//node_modules//' + phantomPackage._location + '//lib//phantom//', phantomPackage.bin.phantomjs)`

just two slashes after node_modules.

Thanks
Silvio

**Comment by dignifiedquire** [comment]
Sorry about that, just pushed `1.0.4`
