### ISSUE TITLE
It is possible, somehow to use phantomjs features when using karma?

### ISSUE THREAD

**Issue by hrodic** [karma-runner/karma-phantomjs-launcher#19]
I am pretty new to Angular/Karma, and i really like the e2e testing. I am really interesting in making the e2e test with jasmine to capture an screenshot if the test fails.
I saw this thread: https://github.com/karma-runner/karma-phantomjs-launcher/issues/7
But is not clear to me if there is any chance to achieve that phantomjs api calls from the karma e2e tests.

---

WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
INFO [karma]: Karma v0.10.4 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.2 (Linux)]: Connected on socket a45DjROxS2bW27aw0lQP
LOG: 'Hello, world!'
PhantomJS 1.9.2 (Linux) ERROR
    ReferenceError: Can't find variable: phantom
    at ****/test/e2e/phantomscenarios.js:4
PhantomJS 1.9.2 (Linux): Executed 0 of 0 ERROR (0.247 secs / 0 secs)

The config file:

---

module.exports = function(config){
    config.set({

```
basePath : '../',

files : [
    'test/e2e/**/*.js'
],

autoWatch : false,

//browsers : ['Chrome'],
browsers:  ['PhantomJS'],

frameworks: ['ng-scenario'],

singleRun : true,

proxies : {
  '/': 'http://localhost:8000/'
},

plugins : [
        'karma-junit-reporter',
        'karma-chrome-launcher',
        'karma-firefox-launcher',
        'karma-jasmine',
        'karma-ng-scenario',
        'karma-phantomjs-launcher'
        ],

junitReporter : {
  outputFile: 'test_out/e2e.xml',
  suite: 'e2e'
}
```

})}

Thanks for the help

**Comment by viveleroi** [comment]
@jamie-pate How are you able to get that script to work? karma-phantomjs-launcher uses PhantomJS 1.9.8 and that code triggers `TypeError: 'undefined' is not a function (evaluating 'Function.prototype.call.bind(Object.prototype.hasOwnProperty)')`. Even once that's dealt with, it triggers `TypeError: Unable to delete property.`

**Comment by jamie-pate** [comment]
Probably need es5-shim to fix that first problem.
For the second problem you could add a try/catch around the delete.

**Comment by tmaiaroto** [comment]
+1 on this. Being able to trigger events would be **very** helpful for testing certain things.

**Comment by FezVrasta** [comment]
I've found a super easy way to take screenshots while using Karma and PhantomJS

http://stackoverflow.com/a/34695107/2059996

**Comment by twolfson** [comment]
For anyone curious, we can take @FezVrasta's solution and go one step further by leveraging `window.open` to skip the Karma header:

```js
// Use `window.open` instead of `iframe` for screenshots
client: {
  useIframe: false
},

// Define custom browser
// DEV: This varies from @FezVrasta's solution by hooking onto page creation
//   As an added bonus, there is no "global" looking `page` variable :+1:
browsers: ['PhantomJSScreenshot'],
customLaunchers: {
  // https://github.com/karma-runner/karma-phantomjs-launcher/issues/19
  // http://stackoverflow.com/questions/34694765/take-screenshot-from-karma-while-running-tests-in-phantomjs-2/34695107#34695107
  // http://phantomjs.org/api/webpage/handler/on-page-created.html
  PhantomJSScreenshot: {
    base: 'PhantomJS',
    options: {
      onPageCreated: function (newPage) {
        newPage.onCallback = function (data) {
          if (data.type === 'render') {
            // Prevent us from writing to any absolute paths or ones that go up a directory
            // DEV: Unforuntately, this throw will be silent
            if (data.filename.indexOf('/') !== -1 || data.filename.indexOf('..') !== -1) {
              throw new Error('Malicious filename found: ' + data.filename);
            }
            newPage.render('path/to/screenshots/' + data.filename + '.png');
          }
        };
      }
    }
  }
}
```

**Comment by rickyp-ms** [comment]
Hey everyone, I've been trying to do a similar thing for accessibility tab testing but the instructions here don't seem to be working for my project. I've created an example repo so that once it's figured out we can have a building example, not just code snippets.

https://github.com/rickyp-ms/example-karma-phantom-callPhantom-sendEvent

I'm hoping someone here can look at this project and help me figure out what exactly is going wrong and why callPhantom (and windowName for that matter) isn't actually executing.

**Comment by twolfson** [comment]
@rickyp-ms Your code is fine but the PhantomJS options don't hook into Karma so `console.log's` and errors are silent. This is due to Karma performing its overrides via scripts on the Karma page; Karma overrides the browser's `console.log` but these options are in the browser window launcher

If I simplify your code to the following, then we successfully generate a screenshot:

**karma.conf.js:**

```js
      'PhantomJS_custom': {
        base: 'PhantomJS',
        options: {
          onPageCreated: function (newPage) {
            newPage.onCallback = function (data) {
              if (data.type === 'render') {
                newPage.render('foo.png');
              }
            };
          }
        }
      }
```

**attempt.test.js:**

```js
        expect(window.callPhantom).to.exist;
        window.callPhantom({ type: 'render' });
```

**Comment by rickyp-ms** [comment]
Thanks for the clean up, that worked amazingly! I'll push the change soon and leave it up if anyone else wants to branch and play.
