### ISSUE TITLE
Karma, PhantomJS : Disconnected during run, waiting for reconnecting.

### ISSUE THREAD

**Issue by calystoramesh** [karma-runner/karma-phantomjs-launcher#20]
already I reported this issue in Karma, But i feel this correct place to log this issues , 

myconf.js 

     PhantomJS_without_security: {
                base: 'PhantomJS',
                options: {
                    windowName: 'PhantomJS (debug)'
                },
                flags: ['--remote-debugger-port=9000']
            }

browsers: ['PhantomJS_without_security'],

then karma start with myconf.js 

DEBUG [launcher]: C:\Documents and Settings\sweet\Application Data\npm\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\phantomjs.exe --remote-debugger-port=9000 C:\DOCUME~1\sweet\LOCALS~1\Temp\karma-29591838/capture.js

open the Chrome with address URL : http://localhost:9000/
click about:blank
in console : "__run()"

DEBUG [PhantomJS 1.9.2 (Windows XP)]: Disconnected during run, waiting for reconnecting.
WARN [PhantomJS 1.9.2 (Windows XP)]: Disconnected

Chrome console :
Event
bubbles: false
cancelBubble: false
cancelable: false
clipboardData: undefined
currentTarget: WebSocket
defaultPrevented: false
eventPhase: 0
returnValue: true
srcElement: WebSocket
target: WebSocket
timeStamp: 1384407329140
type: "error"
__proto__: Event

I am new to PhantomJS . not clear where the problem is occurs , Please some help to me . Stuck with 1 week in this issues

**Comment by jzacsh** [comment]
calystoramesh@, did you ever manage to get more helpful output from karma and move past this?

**Comment by hf-jmetze** [comment]
I did encounter the same problem and hunted it down to the test function name (qunit). I was using a umlaut (ü in my case) and that crashed phantomjs (chrome was working fine). Maybe this helps someone else.

**Comment by Dignifiedquire** [comment]
Closing this down, as it seems to be an underlying issue with phantomjs/the tests being run.
