### ISSUE TITLE
Failed to run tests in phantom after upgrading to ng6

### ISSUE THREAD

**Issue by TKul6** [karma-runner/karma-phantomjs-launcher#215]
Hi,

I've recently upgraded my project to ng 6, and since then I'm experiencing difficulties running tests in Phantom.

When I change the launcher browser to Chrome everything works fine.

When I'm running the tests in Phantom However it fails and says: `SyntaxError: Use of reserved word 'import'`

**karama.conf** : 
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-phantomjs-launcher'),
      require('karma-teamcity-reporter')

    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'), reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress'],

    port: 9877,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false,
    browserNoActivityTimeout: 60000

  });
};

**test.ts**
//import './polyfills.ts';

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare var __karma__: any;
declare var require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();

Do you have any suggestions why the problem happening (or how to fix it)?

Thanks

**Comment by johnjbarton** [comment]
TypeScript has to be compiled to JavaScript, either before the test or in a karma plugin.

**Comment by TKul6** [comment]
Wait I don't get it, up until ng6 it worked perfectly, why know I need to compile the ts to js by myself? When I'm running Karma it builds the angular modules, doesn't it mean it compile them to js?

I also think it should be in the documentation...

Thanks,

**Comment by johnjbarton** [comment]
> up until ng6 it worked perfectly

Then I suggest you look into "ng6".   This issue is not related to karma.
