### ISSUE TITLE
Phantomjs not registered

### ISSUE THREAD

**Issue by jmwood040** [karma-runner/karma-phantomjs-launcher#3]
I  am trying to set up automated testing using;

*Jenkins
*karma
*karma-launcher-phantomjs

When I run:

```
karma start karma-jenkins.conf.js
```

I get:

```
INFO [karma]: Karma v0.9.2 server started at http://localhost:9876/
WARN [launcher]: Launcher "phantomjs" is not registered!
```

My Google searches have not turn up anything.

Here are the details of my setup. 
Please let me know it there is anything else I can provide.

James

---

OS = CentOS 5.9 64 bit
Selinux Disabled

```
node -v
v0.10.5
```

Installed from source

```
npm -v
1.2.18
```

Came with nodejs above

```
phantomjs --version
1.8.2
```

Executable located w/in karam-launcher

---karma-jenkins.conf.js---
'''
basePath = '../';
frameworks = ['jasmine']
files = [
  'app/lib/angular/angular.js',
  'app/lib/angular/angular-_.js',
  'test/lib/angular/angular-mocks.js',
  'app/js/__/_.js',
  // this is a local copy of a dradis-provided module, if e2e fail and unit tests pass, check if
  // these files are out of sync
  'test/unit/websockets.js',
  // used to simplify common test data tasks
  'test/unit/mockData.js',
  'test/unit/*_/_.js'
];

autoWatch = false;
singleRun = true;

browsers = ['phantomjs'];

junitReporter = {
  outputFile: 'test_out/unit.xml',
  suite: 'unit'
};
'''

**Comment by brenwell** [comment]
I had `PhantomJs` not `PhantomJS` thanks @RobbinHabermehl

**Comment by yogee412** [comment]
that's it ,thanks @RobbinHabermehl

**Comment by ellechir** [comment]
Thank you! This fixed the error: plugins = ['karma-phantomjs-launcher'];

**Comment by chrisdothtml** [comment]
I was able to fix this by installing `karma-phantomjs-launcher`. Why do the [config docs](https://karma-runner.github.io/latest/config/configuration-file.html) say that the PhantomJS launcher is installed with Karma if we need to add it in ourselves?

**Comment by silviotroia** [comment]
plugins : ['karma-jasmine', 'karma-phantomjs-launcher'] in karma.conf.js file. Tnx a lot
