### ISSUE TITLE
0.1.3: Cannot start PhantomJS

### ISSUE THREAD

**Issue by gillius** [karma-runner/karma-phantomjs-launcher#31]
After upgrading 0.1.2 to 0.1.3, I get the error message:

```
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.2 server started at http://localhost:9001/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: Cannot start PhantomJS

INFO [launcher]: Trying to start PhantomJS again (1/2).
ERROR [launcher]: Cannot start PhantomJS

INFO [launcher]: Trying to start PhantomJS again (2/2).
ERROR [launcher]: Cannot start PhantomJS

ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
Warning: Task "karma:unit" failed. Use --force to continue.
```

There's no delays between the starting and cannot start messages.

I'm using "^0.1.2" dependency on karma-phantomjs-launcher so I had 2 systems yesterday upgrade to 0.1.3. One is Windows XP and the other Windows 7, both are running nodejs 0.10.26 and phantomjs 1.9.7. On one system phantomjs is in the path, in the other case, karma-phantomjs-launcher is using the version it downloaded itself into its lib folder. I'm running this from grunt. Initially I was using karma 0.10 but tried to upgrade to 0.12.2 to resolve the error with no luck.

Ultimately, I discovered that reverting karma-phantomjs-launcher to 0.1.2 fixes the problem. If I "npm install karma-phantomjs-launcher@0.1.2" then build works, if I install 0.1.3 then it fails. This is consistent even when starting from existing project or when deleting all node_modules and allowing npm to totally refresh everything.

**Comment by xun91** [comment]
+1 `libfontconfig` thanks

**Comment by tschaub** [comment]
[This gist](https://gist.github.com/julionc/7476620) got me set up for Ubuntu 12.04.5.  These were the missing packages:
```
	apt-get install \
			build-essential chrpath libssl-dev libxft-dev \
			libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
```

**Comment by affablebloke** [comment]
+1 on libfontconfig works

**Comment by paulbhartzog** [comment]
+1 on libgontconfig
sudo apt-get install libfontconfig

**Comment by rachelcheuk** [comment]
+1 on libfontconfig works

**Comment by hao1939** [comment]
+1 on libfontconfig, thanks @bitwit !

**Comment by tornabene** [comment]
thanks 
libfontconfig installation worked for me as well :+1: (14.04 LTS)

**Comment by franleplant** [comment]
I was having the same problem and it was solved by `sudo apt-get install libfontconfig`

**Comment by tot-ra** [comment]
Got same problem, karma-phantomjs-launcher: 0.1.4 , phantomjs: 1.9.8 on centos, and libfontconfig is not available

**Comment by mdichirico** [comment]
For CentOS:
sudo yum install freetype
sudo yum install fontconfig
I found that info from this helpful page: http://www.sameerhalai.com/blog/how-to-install-phantomjs-on-a-centos-server/

**Comment by Dignifiedquire** [comment]
I'm closing this issue as it seems all remaining problems are due to the installation process of phantomjs. Please file a new issue if there is something we can actually do to help with this.

**Comment by martinsznapka** [comment]
+1 on libfontconfig (fixed my Docker image)

**Comment by puffnfresh** [comment]
The problem for NixOS is that the /lib64/ld-linux-x86-64.so.2 interpreter doesn't exist. The solution is to have the phantomjs derivation from nixpkgs in your shell, `npm install phantomjs` will find the existing binary.

**Comment by danielyaa5** [comment]
`npm install phantomjs` fixed this for me on Mac OS X

**Comment by arikogan** [comment]
Thanks a lot for the tip @jan-tomsa, libfontconfig did the trick.

**Comment by sg28** [comment]
I faced the same issue,the solution that worked for me is to run
sudo yum install fontconfig ,
The command has to be executed at the right location ,but this Works..

**Comment by roomond** [comment]
Having this issue with suggested solution of *fontconfig, *freetype on Ubuntu 14.04 and with:

`"karma-phantomjs-launcher": "1.0.0",
 "phantomjs": "1.9.8",`

**Comment by deltreey** [comment]
I don't know why fontconfig works, but it works for me too.

**Comment by volosovich** [comment]
in local directory run `npm install phantomjs`
it works for me
MacOs 10.11.6

**Comment by LironHazan** [comment]
npm install phantomjs for MacOs didn't solve it for me
