### ISSUE TITLE
Unable to launch phantomjs

### ISSUE THREAD

**Issue by piyushchauhan2011** [karma-runner/karma-phantomjs-launcher#36]
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.16 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: Cannot start PhantomJS
	
INFO [launcher]: Trying to start PhantomJS again (1/2).
ERROR [launcher]: Cannot start PhantomJS
	
INFO [launcher]: Trying to start PhantomJS again (2/2).
ERROR [launcher]: Cannot start PhantomJS
	
ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
Warning: Task "karma:unit" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2014-05-29 08:56:18 UTC)
karma:unit   97.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 97.8s
-----------------------------------

PhantomJS: 1.9.2
karma-phantomjs-launcher: 0.1.4
Node: 0.10.28
NPM: 1.4.13
OS: GhostBSD-3.5 ( FreeBSD 9.2 release )
Shell: Fish

**Comment by tschaub** [comment]
Has anybody had luck launching PhantomJS on Ubuntu 12.04.5 with Node 0.10.32?  I get output similar to the log above (see https://github.com/karma-runner/karma-phantomjs-launcher/pull/50#issue-53320704).  In addition to `nodejs`, I've installed `libfontconfig1`, `fontconfig`, `libfontconfig1-dev`, and `libfreetype6-dev` debs.

**Comment by Dignifiedquire** [comment]
I'm closing this issue as it seems all remaining problems are due to the installation process of phantomjs. Please file a new issue if there is something we can actually do to help with this.

**Comment by naveen-yadav** [comment]
even I am facing the same issue only the error message is little different while running karma tests on jenkins

```
[31m01 06 2018 07:24:58.202:ERROR [launcher]: [39mCannot start PhantomJS
	Auto configuration failed
140437220120352:error:0200100D:system library:fopen:Permission denied:bss_file.c:169:fopen('/etc/ssl/openssl.cnf','rb')
140437220120352:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:174:
140437220120352:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:199:
```
