### ISSUE TITLE
Cannot install with npm v2.0

### ISSUE THREAD

**Issue by nyarly** [karma-runner/karma-phantomjs-launcher#42]
NPM 2.0 is more strict with semver, so the ~1.9 dependency on phantomjs doesn't match any of the available versions, which are all of the form "<phantomjs_version>-module_version" e.g. 1.9.7-15 is current.

While that versioning is sensible, it causes npm to treat phantomjs as eternally pre-release, so no version of the phantomjs node module satisfies the dependency on karma-phantomjs-launcher.

Ideally the phantomjs team will fix their versions, but in the meantime, could the launcher pin to a particular version e.g "^1.9.7-15" ?

**Comment by MerlierR** [comment]
+1

**Comment by Dignifiedquire** [comment]
Should be fixed by #70
