### ISSUE TITLE
PhantomJS 2

### ISSUE THREAD

**Issue by oanuna** [karma-runner/karma-phantomjs-launcher#46]
Any plans to integrate the use of PhantomJS 2 so ES6 scripts can be run and tested against?

**Comment by gskachkov** [comment]
@oanuna  As I know Phantom JS 2 is still in development, however you can use **karma-phantomjs2-launcher** that can run of beta version of [PhantomJS 2] (https://github.com/bprodoehl/phantomjs/releases/). It is fork of *karma-phantomjs-launcher*
As for now it supports Linux & Mac OS, I hope in nearest feature it will support Windows.
I've checked on Mac OS X 10.9.5. Also  I didn't hear about supporting es6 in PhantomJS2 only full support of es5. 

To install 
```
npm install  karma-phantomjs2-launcher
```
make sure that **PhantomJS2** in list of browsers  in karma.conf.js
``` javascript
browsers: ['PhantomJS2']
```

**Comment by oanuna** [comment]
I believe es6 features will come along when integration with V8 or the latest QtWebkit, but that remains to be seen. Thanks for the update though @gskachkov

**Comment by gskachkov** [comment]
@oanuna  If you are interested in testing es6 features, you can play with [slimerjs](http://slimerjs.org) that is headless Firefox. There is launcher for it **karma-slimerjs-launcher**.

**Comment by oanuna** [comment]
@gskachkov now you're just spoiling me!
Thanks I'll have a good look at it

**Comment by tlightsky** [comment]
need es6 support too

**Comment by gskachkov** [comment]
@tlightsky  I've seen a lot of finished  es6 features in WebKit codebase for instance 'class'. So I hope that they will be included in nearest releases of PhantomJS.

**Comment by tlightsky** [comment]
I see, I mean that too :)

**Comment by sepprenfer** [comment]
gosh! need it as well :)

**Comment by nshahpazov** [comment]
+1

**Comment by hsd99** [comment]
+1

**Comment by lathonez** [comment]
+1

**Comment by sudolife** [comment]
+2

**Comment by lathonez** [comment]
I'm using `PhantomJS2` and `karma-phantomjs2-launcher` as suggested by @gskachkov and it's working well.

My setup is heavily based on [mgechev/angular2-seed](https://github.com/mgechev/angular2-seed)

**Comment by julmot** [comment]
+1

**Comment by deddu** [comment]
@lathonez that link is using chrome. Can you paste the significant lines of your config? 
`PhantomJS2` and `karma-phantomjs2-launcher` still choke at the first `let` .

**Comment by lathonez** [comment]
Check out our demo / seed project https://github.com/lathonez/clicker. My karma conf https://github.com/lathonez/clicker/blob/master/test/karma.config.js

**Comment by jainrahulkumar** [comment]
not working for me same error for Es6 code
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token '>'
  at app/client/planroom/header.js:9
