### ISSUE TITLE
Phantomjs crashed after >10 seconds

### ISSUE THREAD

**Issue by kamalpatel125** [karma-runner/karma-phantomjs-launcher#54]
Hi,

It seems like phantomjs crashing after 10 second. Is it possible to increase the timeout limit ? 

Thanks & Regards,

Kamal Patel.

**Comment by thomaswmanion** [comment]
This is actually configurable within the Karma Configuration: browserNoActivityTimeout.

**Comment by kamalpatel125** [comment]
Thanks for you answer.
