### ISSUE TITLE
Cannot find module (Documents folder)\install.js

### ISSUE THREAD

**Issue by chaim1221** [karma-runner/karma-phantomjs-launcher#60]
Yo.

Trying to install Karma with the PhantomJS launcher on Win8.1x64.

It works on everyone else's machine. Here are the steps we're taking:

Install Node via .msi for 64 bit

`npm install karma --save-dev`
`npm install karma-jasmine`
`npm install -g karma-cli`

Download PhantomJS static binary from http://phantomjs.org/download.html

`npm install karma-phantomjs-launcher`

And that's where, on my machine, for some reason I cannot figure out (I have checked `SET` and `ENV`, etc.), I get the following error:
```
npm install karma-phantomjs-launcher
-
> phantomjs@1.9.15 install C:\InComm\enterprise-apps\Web\Admin\Scripts\Tests\node_modules\karma-phan
tomjs-launcher\node_modules\phantomjs
> node install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\celiyah\Documents\install.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\celiyah\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "karma-phantomjs-launcher"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.15 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\InComm\enterprise-apps\Web\Admin\Scripts\Tests\npm-debug.log
```
I checked with the phantomjs folks and they say it is not their issue since npm isn't even getting to the phantomjs install package, but when I try to install phantomjs I get the same error.

Frustratingly, `npm install karma-chrome-launcher` works fine.

**Comment by Dignifiedquire** [comment]
Could you try installing phantomjs 2 manually? Also what is the output when you install phantomjs on its own?

**Comment by chaim1221** [comment]
Yo, left this in the wrong thread, so reposting it here:

Kind of a strange directory setup anyway. I had a problem for months in a windows environment with Node. Kept looking in my Documents folder for install.js for dependencies, even when the bloomin' version was defined in the original install.js deps. Anyways, my final solution to all these Node EPERM or ENOENT errors on Windows (really):

Nuke Windows. Start over. Install Node.js fresh. Globally install NPM. Disable original NPM (where npm). Globally install your command line utilities (e.g., karma-cli). Then install anything else you need.

Still trying to figure out whether to blame Ballmer or Dahl.

**Comment by Dignifiedquire** [comment]
Thanks for the answer, sounds like computers were doing what computers can do best, not working..
