### ISSUE TITLE
Update PhantomJS to 2.0 

### ISSUE THREAD

**Issue by zckrs** [karma-runner/karma-phantomjs-launcher#64]
Can you update PhantomJS to the latest stable release ? http://phantomjs.org/release-2.0.html 

https://github.com/Swiip/generator-gulp-angular/pull/405

**Comment by tplorts** [comment]
:+1:

**Comment by tplorts** [comment]
duplicate of #56 - note in there about the hold up

**Comment by maksimr** [comment]
Close as duplicate
