### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by ghost** [karma-runner/karma-phantomjs-launcher#7]
When I run PhantomJS using following command

phantomjs /test/phantom/colorwheel.js

{works fine}

But when I try to run the same file through Karma I am getting following error,

ReferenceError: Can't find variable: require

Any idea what could be possible issue -

```
Is it something not possible to do ?

Am I missing some config on Karma, Here is code from karma.conf.js
```

module.exports = function(karma) {
karma.set({
basePath: '',
frameworks: ['jasmine'],
files: [
'test/phantom/colorwheel.js',
],

// list of files to exclude
exclude: [

],
reporters: ['progress'],
port: 9876,
runnerPort: 9100,
colors: true,

logLevel: karma.LOG_INFO,

autoWatch: true,

browsers: ['PhantomJS'],

captureTimeout: 60000,

singleRun: false

});
};

Node version - v0.10.12
Karma version: 0.9.4
PhantomJS - 1.9.1
OS - Mac OS X

**Comment by ibbatta** [comment]
Thanks @vojtajina you save my day!
