### ISSUE TITLE
Remove peerDependencies

### ISSUE THREAD

**Issue by monolithed** [karma-runner/karma-phantomjs-launcher#71]
```
npm WARN peerDependencies The peer dependency karma@>=0.9 included from karma-phantomjs-launcher will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

In short, peerDependencies should probably be removed:
See for context: npm/npm#6565

**Comment by Dignifiedquire** [comment]
I don't think we will remove peerDependencies. As you can see in the discussion in https://github.com/npm/npm/issues/6565 peerDependencies will still lock down the version you are using together with the plugin (i.e. the version of karma combined with karma-phantomjs-launcher). The only difference that there will be is that when you install karma-phantomjs-launcher on its own it will not automatically pull down a version of karma, which is actually a good thing.

**Comment by lookfirst** [comment]
It would be nice to not have to see that warning every time I run npm install.

**Comment by MarkLeMerise** [comment]
I think I am confused. Shouldn't `phantomjs` be a direct `dependency` since it is used directly by the plugin? The plugin would fail to load without it, no?

**Comment by antwan1986** [comment]
Yeah I'm also confused on this, so whenever NPM v3 releases, will end users of this package be expected to install PhantomJS themselves? e.g.

```
"devDependencies": {
    "karma-phantomjs-launcher": "0.2.0",
    "phantomjs": "1.9.17"
}
```

In my opinion this would be a good thing to do as it'll allow people to swap out to PhantomJS 2.0 easily (depending of course on any API / interfacting problems with this package).

**Comment by Dignifiedquire** [comment]
@antwan1986 yes that is exactly the idea.

**Comment by antwan1986** [comment]
Sounds awesome!

**Comment by mpelzsherman** [comment]
Won't keeping peerDependencies will prevent users from upgrading to npm 3.X? I'm fairly new to npm so I might be confused on this issue. Thanks!

**Comment by monolithed** [comment]
It seems we should close the issue. 
[Flat package structure](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) in npm 3 is awesome :+1:
