### ISSUE TITLE
Can't make CORS work

### ISSUE THREAD

**Issue by emirotin** [karma-runner/karma-phantomjs-launcher#74]
PhantomJS rejects my cross-domain XHR requests despite the fact I configure it with disabled security.

Here's the repo https://github.com/IsoldaJS/isolda-browser-ajax. As you can see I try both CLI flag and the in-browser setting (I also tried them individually). My tests fail because the CORS request is rejected by the browser and they expect server error 400 instead.

To prove that it's not an issue with my code here's a branch that uses Chrome launcher https://github.com/IsoldaJS/isolda-browser-ajax/tree/test-chrome. Tests pass OK

**Comment by Dignifiedquire** [comment]
You probably need to add a [flag](http://phantomjs.org/api/command-line.html) for `--web-security=false` to make this work

**Comment by emirotin** [comment]
@Dignifiedquire 

> As you can see **I try both CLI flag and the in-browser setting** (I also tried them individually). 

https://github.com/IsoldaJS/isolda-browser-ajax/blob/master/karma.conf.js#L55

**Comment by Dignifiedquire** [comment]
> > As you can see I try both CLI flag and the in-browser setting (I also tried them individually).

Really sorry, still a bit tried, will check it out

**Comment by emirotin** [comment]
No problem, really looking forward resolving this as I'd like to use karma
and phantom as a standard testing env for all my new projects

**Comment by Dignifiedquire** [comment]
Alright, I got it fixed, looks like phantomjs is even more annoying than I thought. You have to pass this config to it to make it work:

```
flags: [
  '--web-security=false',
  '--ignore-ssl-errors=true'
]
```

It seems because you are requesting a url that is `https` it fails if you don't enable this. With that config I got your test project working.

**Comment by emirotin** [comment]
Thanks a lot. That helps indeed. Even worse only the SSL flag is needed, CORS works on its own, but (unexpectedly) without the SSL flag the error thrown is CORS rejection.

Anyway thanks for your help again.

**Comment by rashi04** [comment]
Hi,
the replies in the post helped me in solving my issue . But My CORS url needs username and password. IS there any configuration which can help me here?
