### ISSUE TITLE
After upgrade to 0.3.0: Karma error: "Can not load 'PhantomJS', it is not registered!"

### ISSUE THREAD

**Issue by rickhuizinga** [karma-runner/karma-phantomjs-launcher#8]
After upgrading to ng-boilerplate 0.3.0, with its updated dependency on grunt-karma 0.5.0, the grunt process stops with a Karma warning: "Can not load 'PhantomJS', it is not registered!".

The problem is that the plugins line of karma-unit.tpl.js only has 'karma-firefox-launcher' and 'karma-chrome-launcher'.  Updating it to add 'karma-phantomjs-launcher' will fix the problem.

**Comment by stephaneeybert** [comment]
Make sure both karma and its plugins are installed either all locally or all globally.
