### ISSUE TITLE
Failed to installed PhantomJS Dependency

### ISSUE THREAD

**Issue by RDalziel** [karma-runner/karma-phantomjs-launcher#85]
I'm getting this error when i'm trying to install Karma-phantomjs-launcher:

karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.

Any ideas how to get round this aside from adding PhantomJS to package.json? I'd like for PhantomJS to be aligned with the version of Karma-phantomjs-launcher that's installed.

I'm using the latest version of npm - 3.3.9

**Comment by RDalziel** [comment]
Even when it is installed manually, it has issues finding PhantomJS,

This is on a Windows 2012 server btw. Seems very inconsistent with its behaviours

**Comment by kvzivn** [comment]
Having the same issue.

**Comment by aciccarello** [comment]
I had the same error when first installing Karma-phantomjs-launcher. I think adding PhantomJS to package.json is a suitable solution for now but I do understand the desire to not have to manage the dependency.

I ran `npm install --save-dev phantomjs@>=1.9` on npm 3.3.12 running on Windows 7 and the launcher recognized PhantomJS.

**Comment by dignifiedquire** [comment]
If you are on npm@3 peer dependencies have to be installed manually for npm@2 they are installed automatically.
