### ISSUE TITLE
Document the options attribute

### ISSUE THREAD

**Issue by danielsiwiec** [karma-runner/karma-phantomjs-launcher#89]
I spent hours digging through the net and eventually the source code figuring out how to set properties on the phantomjs page object via karma, just to find out that it's really simple (the options attribute).

I find it super useful and think it should be mentioned in the documentation. I'm happy to submit a PR for it if there's agreement.

**Comment by Dignifiedquire** [comment]
Thanks for pointing this out, PRs to improve the documentation are always welcome :)
