### ISSUE TITLE
Incorrect passing of option flags to phantomjs

### ISSUE THREAD

**Issue by kenborge** [karma-runner/karma-phantomjs-launcher#94]
Hi.
With the changes in the newest version option flags passed to phantomjs no longer work. In this PR #91 it was changed so flags are added after the script file but this is wrong it needs to be before the script file. 
From the phantomJS documentation:
```
phantomjs [options] somescript.js [arg1 [arg2 [...]]]
```
So using ```flags: ['--load-images=false']``` no longer works now. It also causes a lot of out tests to actually crash if we try to use flags. I'm guessing because it's parsing the flags we use as arguments and something goes wrong.

This is also what's causing issue #92

**Comment by Dignifiedquire** [comment]
Thanks for the report

**Comment by Dignifiedquire** [comment]
Should be fixed in `0.2.3`
