### ISSUE TITLE
Upgrade to phantomjs2 as the default

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma-phantomjs-launcher#97]

**Comment by Havunen** [comment]
:+1:

**Comment by zowers** [comment]
I believe you mean phantomjs-prebuilt - the new phantomjs npm package depending on phantomjs 2.1
https://github.com/karma-runner/karma-phantomjs-launcher/pull/98

**Comment by dignifiedquire** [comment]
Fixed in #98
